package org.firstinspires.ftc.robotcontroller.internal;

//wat

final class FtcRobotRegistrar {
    /**
     * This class is where robot classes need to be registered, using the FULL PATH to them in order
     * for said classes to have their configuration files autogenerated. For your convenience, the
     * path to the Robots package has already been defined as ROBOTS_PACKAGE. Robot classes are
     * classes found in the org.firstinspires.ftc.teamcode.hardware.Robots package THAT EXTEND
     * org.firstinspires.ftc.teamcode.hardware.RobotInterfacesAndAbstracts.Robot. Ideally these
     * classes implement interfaces so as to decouple them from OpModes, but this is not required
     * for configuration file auto-generation. The details for configuration file auto-generation
     * MUST be correctly inputted to the
     * org.firstinspires.ftc.teamcode.xmlio.XMLUTils.generateDocument method by the
     * extensions of org.firstinspires.ftc.teamcode.hardware.RobotInterfacesAndAbstracts.Robot
     * in order for auto-generation to work. Examples of how to do this can be found in the
     * pre-existing code.
     */

    private static final String ROBOTS_PACKAGE = "org.firstinspires.ftc.teamcode.hardware.Robots.";

    private static final String[] ROBOT_REGISTRAR = {
            ROBOTS_PACKAGE + "BotMarkI",
            ROBOTS_PACKAGE + "BotMarkII",
            ROBOTS_PACKAGE + "BotMarkIII"
    };

    static void autoGenerateConfigurations() {
        for (String robot : ROBOT_REGISTRAR) {
            try {
                Class robotClass = Class.forName(robot);

            } catch (Exception e) {
                //LogUtils.logError(e.getMessage());
            }
        }
    }

}
